"""Classification pipelines: person, vehicle, face, and generic object processing."""

from percept.pipelines.router import (
    PipelineType,
    RouterConfig,
    RoutingDecision,
    PipelineRouter,
    RouterModule,
    get_pipeline_for_class,
    PERSON_CLASSES,
    VEHICLE_CLASSES,
)
from percept.pipelines.person import (
    Posture,
    PersonPipelineConfig,
    Keypoint,
    PoseResult,
    ClothingResult,
    PoseEstimator,
    ClothingAnalyzer,
    FaceDetector,
    PersonPipeline,
    PersonPipelineModule,
    KEYPOINT_NAMES,
    KEYPOINT_INDICES,
)
from percept.pipelines.vehicle import (
    VehicleType,
    VehicleOrientation,
    VehiclePipelineConfig,
    VehicleColorResult,
    VehicleTypeResult,
    LicensePlateResult,
    VehicleColorAnalyzer,
    VehicleTypeClassifier,
    LicensePlateDetector,
    VehiclePipeline,
    VehiclePipelineModule,
)
from percept.pipelines.generic import (
    GenericPipelineConfig,
    ClassificationResult,
    ColorResult,
    ShapeResult,
    ImageNetClassifier,
    ColorAnalyzer,
    ShapeAnalyzer,
    SizeEstimator,
    GenericPipeline,
    GenericPipelineModule,
)

__all__ = [
    # Router
    "PipelineType",
    "RouterConfig",
    "RoutingDecision",
    "PipelineRouter",
    "RouterModule",
    "get_pipeline_for_class",
    "PERSON_CLASSES",
    "VEHICLE_CLASSES",
    # Person
    "Posture",
    "PersonPipelineConfig",
    "Keypoint",
    "PoseResult",
    "ClothingResult",
    "PoseEstimator",
    "ClothingAnalyzer",
    "FaceDetector",
    "PersonPipeline",
    "PersonPipelineModule",
    "KEYPOINT_NAMES",
    "KEYPOINT_INDICES",
    # Vehicle
    "VehicleType",
    "VehicleOrientation",
    "VehiclePipelineConfig",
    "VehicleColorResult",
    "VehicleTypeResult",
    "LicensePlateResult",
    "VehicleColorAnalyzer",
    "VehicleTypeClassifier",
    "LicensePlateDetector",
    "VehiclePipeline",
    "VehiclePipelineModule",
    # Generic
    "GenericPipelineConfig",
    "ClassificationResult",
    "ColorResult",
    "ShapeResult",
    "ImageNetClassifier",
    "ColorAnalyzer",
    "ShapeAnalyzer",
    "SizeEstimator",
    "GenericPipeline",
    "GenericPipelineModule",
]
